### ISSUE TITLE
Crashes on Home-bridge start 

### ISSUE THREAD

**Issue by eryk4pdh** [volca/homebridge-esplock#9]
Hello, 

I have 3 other platforms running on HB (nest, lightwaver RF and HUE) when I added installed the plugin using :
`sudo npm install -g homebridge-esplock`

and added to the config.json the following:
```	
{
		"accessory": "EspLock",
		"name": "Front Door",
		"url": "http://192.168.0.51/",
		"lock-id": "1",
		"username": "test",
		"password": "test"
	},
```

I get when i try to launch homebridge

```[2/3/2019, 4:40:07 PM] Loading 4 platforms...
[2/3/2019, 4:40:07 PM] [Hue] Initializing Hue platform...
[2/3/2019, 4:40:07 PM] [Hue] homebridge-hue v0.11.1, node v10.14.0, homebridge v0.4.45
[2/3/2019, 4:40:07 PM] [Hue] warning: not using recommended node version v10.13.0 LTS
/usr/lib/node_modules/homebridge/lib/api.js:108
  if (name.indexOf('.') == -1) {
           ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:108:12)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:316:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:86:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)```

any ideas what I have done wrong? Thanks

**Comment by volca** [comment]
Is the log belong to `homebridge-hue`?

```
[2/3/2019, 4:40:07 PM] [Hue] Initializing Hue platform...
[2/3/2019, 4:40:07 PM] [Hue] homebridge-hue v0.11.1, node v10.14.0, homebridge v0.4.45
[2/3/2019, 4:40:07 PM] [Hue] warning: not using recommended node version v10.13.0 LTS
/usr/lib/node_modules/homebridge/lib/api.js:108
  if (name.indexOf('.') == -1) {
           ^
```

**Comment by eryk4pdh** [comment]
@volca thanks for replying ignore the 3 lines
```
[2/3/2019, 4:40:07 PM] [Hue] Initializing Hue platform...
[2/3/2019, 4:40:07 PM] [Hue] homebridge-hue v0.11.1, node v10.14.0, homebridge v0.4.45
[2/3/2019, 4:40:07 PM] [Hue] warning: not using recommended node version v10.13.0 LTS
```

The esp lock is after hue in my json file, hue loads fine

I have attached two screenshots.
1. I have added esp-lock to my json result **homebridge crash**
![screenshot 2019-02-06 at 21 40 46](https://user-images.githubusercontent.com/17545990/52376047-0ec8b000-2a59-11e9-818d-b4ef046af10b.jpg)

2. I have removed the esp-lock from my json result **homebridge runs**
![screenshot 2019-02-06 at 21 44 30](https://user-images.githubusercontent.com/17545990/52376111-2e5fd880-2a59-11e9-922a-e72e0f077719.jpg)

**Comment by volca** [comment]
Please see the config example. You should move it under the key `accessories` not `platforms`

```
{
  "accessories": [
    {
        "accessory": "EspLock",
        "name": "Front Door",
        "url": "your-custom-or-homegrown-service-url",
		"lock-id": "1",
        "username" : "your-username",
		"password" : "your-password"
    }
  ]
}
```

**Comment by eryk4pdh** [comment]
Sorry, my mistake! It works now! Thank you for your help!
